# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Metal on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build-macos-mtl

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        lfs: true

    - name: Setup shader build environment
      run: |
        sudo pip3 install ninja --break-system-packages

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ env.BUILD_DIR }} 
        -G Ninja 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
        -DGraphicsApi=MTL

    - name: Build Core
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{env.BUILD_TYPE}} --target KryneEngine_Core

    - name: Build Core Unit tests
      run: >
        cmake --build ${{ env.BUILD_DIR }} --config ${{env.BUILD_TYPE}} --target
        Core_Common_UnitTests
        Core_Graphics_UnitTests
        Core_Math_UnitTests
        Core_Memory_UnitTests
        Core_Threads_UnitTests
    
    - name: Upload Core Unit tests
      uses: actions/upload-artifact@v7
      with:
        name: core-unit-tests
        path: ${{ env.BUILD_DIR }}/Tests/Core

    - name: Build Modules
      run: >
        cmake --build ${{ env.BUILD_DIR }} --config ${{env.BUILD_TYPE}} --target
        KryneEngine_Modules_FileSystem
        KryneEngine_Modules_GraphicsUtils
        KryneEngine_Modules_GuiLib
        KryneEngine_Modules_ImGui
        KryneEngine_Modules_RenderGraph
        KryneEngine_Modules_Resources
        KryneEngine_Modules_SdfTexture
        KryneEngine_Modules_ShaderReflection
        KryneEngine_Modules_TextRendering

    - name: Build Modules Unit tests
      run: >
        cmake --build ${{ env.BUILD_DIR }} --config ${{env.BUILD_TYPE}} --target
        Modules_FileSystem_UnitTests
        Modules_GraphicsUtils_UnitTests

    - name: Upload Modules Unit tests
      uses: actions/upload-artifact@v7
      with:
        name: modules-unit-tests
        path: ${{ env.BUILD_DIR }}/Tests/Modules

    - name: Build Samples
      run: >
        cmake --build ${{ env.BUILD_DIR }} --config ${{env.BUILD_TYPE}} --target
        HelloTriangle
        ImGuiDemo
        RenderGraphDemo
        UiDemo

  test-core:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v7
        with:
          name: core-unit-tests
          path: ${{ env.BUILD_DIR }}/Tests/Core

      - name: Restore execute permission
        run: find ${{ env.BUILD_DIR }}/Tests/Modules -type f -name '*UnitTests*' -exec chmod +x {} \;

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}/Tests/Core
        run: ctest -C ${{env.BUILD_TYPE}}

  test-modules:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v7
        with:
          name: modules-unit-tests
          path: ${{ env.BUILD_DIR }}/Tests/Modules

      - name: Restore execute permission
        run: find ${{ env.BUILD_DIR }}/Tests/Modules -type f -name '*UnitTests*' -exec chmod +x {} \;

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}/Tests/Modules
        run: ctest -C ${{env.BUILD_TYPE}}
